apiVersion: v1
kind: Service
metadata: 
    name: sdatabase
    labels:
       app: database-service
spec: 
   selector:
     app: database-service
   ports:
     - protocol: TCP
       port: 5984
       targetPort: 5984
       #name: http
   #type: ClusterIP